config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :todos
  resources :snippets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :todo
end

app/models/snippet.rb
class Snippet < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :comments, :class_name => :Commnet, foreign_key: 'todo_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:comment, :todos_id)
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def snippet_params
      params.require(:snippet).permit(:title, :language, :contents)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    @todos_count = Todo.all.count()
    @commnets_count = Comment.all.count()
    @commnets = Comment.all

    p @commnets
    p @commnets_count

    p @todos_count
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :description, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="field">
    <%= form.label :todos_id %>
    <%= form.number_field :todos_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Todos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.todos_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Todos:</strong>
  <%= @comment.todos_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnippetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/snippets/_form.html.erb
<%= form_with(model: snippet, local: true) do |form| %>
  <% if snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
        <% snippet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :contents %>
    <%= form.text_field :contents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @snippet.title %>
</p>

<p>
  <strong>Language:</strong>
  <%= @snippet.language %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @snippet.contents %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify@1.5/dist/vuetify.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@1.5/dist/vuetify.js"></script>
  <script src="https://cdn.rawgit.com/showdownjs/showdown/1.9.0/dist/showdown.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.8.4/Sortable.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Vue.Draggable/2.23.2/vuedraggable.umd.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/vue2-highcharts@1.2.5/dist/vue-highcharts.min.js"></script>

  <title>todo App</title>
</head>
<body>
<%#= render 'todos/header' %>
<v-app id="app">
  <v-toolbar color="red lighten-3" dark>
    <v-toolbar-title>Todo List</v-toolbar-title>
    <v-spacer></v-spacer>
    <v-btn flat v-on:click="togglePostModal()">New todo</v-btn>
  </v-toolbar>
  <v-container style="height: 100px; max-width: 100%;">
    <v-layout>
      <v-flex xs5>
        <div style="margin:10px">
          <h2>Select title</h2>
          <v-select v-model='description' :items="descrip" label="description" v-on:change="abstruct"></v-select>
          <h2>Todo List</h2>
          <ul>
            <li v-for="todo in todoList"><span id='name' v-on:click="goElem(todo.id)">[{{ todo.id }}] {{ todo.title }}</span></li>
          </ul>
        </div>
      </v-flex>
      <v-flex xs7 style='margin:10px'>
        <h2>Search todo</h2>
        <v-text-field v-model="searchWord" v-on:keyup="abstruct" label="Input Keyword" style='margin-top:4px'></v-text-field>

        <!-- 一覧表示 -->
        <draggable>
          <v-card style="margin-top:10px" v-for="todo in todoList">
            <v-card-title primary-title>
              <a v-bind:id='todo.id'></a>
              <h3 class="headline"> {{ todo.title }}:{{ todo.comment.id }} </h3>
            </v-card-title>
            <div style="margin: 10px 20px;">
              <div v-html='showdown.makeHtml(todo.content)'></div>
            </div>

            <v-card-actions>
              <v-btn flat color="red" v-on:click="toggleDetailsModal(todo.id)">Details</v-btn>
              <v-btn flat color="red" v-on:click="togglePutModal(todo.id)">Detail / Update</v-btn>
              <v-btn flat color="gray" v-on:click="toggleDeleteModal(todo.id)">Delete</v-btn>
              <v-spacer></v-spacer>
              <!--<v-btn flat color="red" v-on:click="goTop">Go Top</v-btn>-->

            </v-card-actions>
          </v-card>
        </draggable>
      </v-flex>
    </v-layout>

    <!-- 詳細 ダイアログ -->
    <v-dialog v-model="dialogdetailFlag" width="800" persistent>
      <v-card>
        <v-card-title class="headline red lighten-3 white--text" primary-title>
          Detail Form
        </v-card-title>
        <v-text-field v-model="detailTitle" label="todo Title" required style='margin:20px; margin-top:30px'></v-text-field>
        <v-flex d-flex>
          <v-text-field v-model="detailDescription" label="description" required style='margin:20px; margin-bottom:0px; margin-left:20px'></v-text-field>
<!--          <v-select v-model='detailDescription' :items="descriptionForEdit" label="Select from history" style='margin:20px; margin-bottom:0px;margin-left: 0px'></v-select>-->
        </v-flex>
        </v-flex>
        <v-card-text>
          <p>todo</p>
          <div style='width:100%;'>
            <textarea style='width:100%; height:300px; background-color:#efefef; padding:3px' v-model='detailContents'></textarea>
          </div>
        </v-card-text>
        <v-divider></v-divider>

        <v-card-actions>
          <v-btn color="#grey lighten-4" flat v-on:click="toggleDetailsModal">
            Cancel
          </v-btn>
          <v-spacer></v-spacer>
          <v-btn color="red" flat v-on:click="togglePutModal(todo.id)">
            更新
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- 作成 ダイアログ -->
    <v-dialog v-model="dialogPostFlag" width="800" persistent>
      <v-card>
        <v-card-title class="headline red lighten-3 white--text" primary-title>
          Create Form
        </v-card-title>
        <v-text-field v-model="postTitle" label="todoTitle" required style='margin:20px; margin-top:30px'></v-text-field>
        <v-flex d-flex>
          <v-text-field v-model="postDescription" label="description" required style='margin:20px; margin-bottom:0px; margin-left:20px'></v-text-field>
<!--          <v-select v-model='postDescription' :items="descriptionForEdit" label="Select from history" style='margin:20px; margin-bottom:0px;margin-left: 0px'></v-select>-->
        </v-flex>
        </v-flex>
        <v-card-text>
          <p>todo</p>
          <div style='width:100%;'>
            <textarea style='width:100%; height:300px; background-color:#efefef; padding:3px' v-model='postContents'></textarea>
          </div>
        </v-card-text>
        <v-divider></v-divider>

        <v-card-actions>
          <v-btn color="#grey lighten-4" flat v-on:click="togglePostModal">
            Cancel
          </v-btn>
          <v-spacer></v-spacer>
          <v-btn color="red" flat v-on:click="postTodos">
            Add todo
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- 更新 ダイアログ -->
    <v-dialog v-model="dialogPutFlag" width="800" persistent>
      <v-card>
        <v-card-title class="headline red lighten-3 white--text" primary-title>
          Edit Form
        </v-card-title>

        <v-text-field v-model="putTitle" label="todo Title" required style='margin:20px; margin-top:30px'></v-text-field>
        <v-flex d-flex>
          <v-text-field v-model="putdescription" label="description" required style='margin:20px; margin-bottom:0px; margin-left:20px'></v-text-field>
        </v-flex>
        <v-card-text>
          <p>todo</p>
          <div style='width:100%;'>
            <textarea style='width:100%; height:300px; background-color:#efefef; padding:3px' v-model='putContents'></textarea>
          </div>
        </v-card-text>

        <v-divider></v-divider>

        <v-card-actions>
          <v-btn color="#grey lighten-4" flat v-on:click="togglePutModal">
            Cancel
          </v-btn>
          <v-spacer></v-spacer>
          <v-btn color="red" flat v-on:click="postTodos">
            Update todo
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- 削除 ダイアログ -->
    <v-dialog v-model="dialogDeleteFlag" width="400">
      <v-card>
        <v-card-title class="headline red lighten-3 white--text" primary-title>
          Confirm
        </v-card-title>
        <v-spacer></v-spacer>
        <v-card-text>
          <p>本当に削除してもよろしいですか？</p>
        </v-card-text>

        <v-divider></v-divider>

        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="red" flat v-on:click="deleteSnippet()">
            Delete
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</v-app>
<script>
    new Vue({
        // el: '#toolbar',
        el: '#app',
        data () {
            return {
                todoList: ['',''],
                allData: ['',''],
                descrip: ['All'],
                descripForEdit: [],
                description: 'ALL',

                //作成
                dialogPostFlag: false,
                postTitle: '',
                postDescription: '',
                postContents: '',

                //詳細
                dialogdetailFlag: false,
                detailTitle: '',
                detailDescription: '',
                detailContents: '',

                //更新
                dialogPutFlag: false,
                putTitle: '',
                putdescription: '',
                putContents: '',

                //削除
                dialogDeleteFlag: false,
                searchWord: ''
            }
        },
        mounted () {
            this.listSnippet();
            options = { headerLevelStart: 3, omitExtraWLInCodeBlocks: true, tables: true, simpleLineBreaks: true, simplifiedAutoLink: true }
            this.showdown = new showdown.Converter(options)
        },
        methods: {
            listSnippet: function() {

                //一覧取得
                axios.get('/todos.json')
                    .then(response => {
                            this.allData = response.data
                            this.todoList = this.allData
                            this.lists();
                            this.abstruct();
                        }
                    );
            },
            lists: function() {
                this.description = []
                this.descripForEdit = []
                this.descrip.push('ALL')
                for (i=0;i<this.allData.length;i++) {
                    if (this.descrip.indexOf(this.allData[i].description) == -1) {
                        this.descrip.push(this.allData[i].description)
                        this.descripForEdit.push(this.allData[i].description)
                    }
                }
            },

            togglePostModal: function() {
                this.dialogPostFlag = !this.dialogPostFlag
            },

            //詳細処理
            toggleDetailsModal: function(id) {
                axios.get('/todos/' + id + '.json')
                    .then(response => {
                            this.detailTitle = response.data.title
                            this.detailDescription = response.data.description
                            this.detailContents = response.data.content
                        }
                    );

                this.id = id
                this.dialogdetailFlag = !this.dialogdetailFlag
            },

            //更新処理
            togglePutModal: function(id) {
                axios.get('/todos/' + id + '.json')
                    .then(response => {
                            this.putTitle = response.data.title
                            this.putdescription = response.data.description
                            this.putContents = response.data.content
                        }
                    );

                this.id = id
                this.dialogPutFlag = !this.dialogPutFlag
            },

            //削除処理
            deleteSnippet: function() {
                axios.delete('/todos/' + this.id + '.json')
                    .then(response => {
                            this.listSnippet();
                        }
                    );
                this.dialogDeleteFlag = !this.dialogDeleteFlag
            },
            toggleDeleteModal: function(id) {
                this.id = id
                this.dialogDeleteFlag = !this.dialogDeleteFlag
            },
            goElem: function(id) {
                document.getElementById(id).scrollIntoView(true)
            },
            goTop: function() {
                document.getElementById("app").scrollIntoView(true)
            },
            abstruct: function() {
                if (this.description == 'ALL') {
                    this.todoList = []
                    for (i=0;i<this.allData.length;i++) {
                        if ((this.allData[i].content.indexOf(this.searchWord) !== -1) || (this.allData[i].title.indexOf(this.searchWord) !== -1) || (this.allData[i].description.indexOf(this.searchWord) !== -1)) { // 説明 4.7
                            this.todoList.push(this.allData[i])
                        }
                    }
                } else if (this.description != '') {
                    this.todoList = []
                    for (i=0;i<this.allData.length;i++) {
                        if (this.allData[i].description == this.description) {
                            if ((this.allData[i].content.indexOf(this.searchWord) !== -1) || (this.allData[i].title.indexOf(this.searchWord) !== -1) || (this.allData[i].description.indexOf(this.searchWord) !== -1)) { // 説明 4.7
                                this.todoList.push(this.allData[i])
                            }
                        }
                    }
                }
            },
            postTodos: function() {
                axios.put('/todos/' + this.id + '.json', {title:this.putTitle, description:this.putdescription, content:this.putContents})
                    .then(response => {
                            this.listSnippet();
                        }
                    );
                this.dialogPutFlag = !this.dialogPutFlag
            },
            postTodos: function() {
                axios.post('/todos.json', {title:this.postTitle, description:this.postDescription, content:this.postContents})
                    .then(response => {
                            this.listSnippet();
                            this.postTitle = ''
                            this.postDescription = ''
                            this.postContents = ''
                        }
                    );

                this.dialogPostFlag = !this.dialogPostFlag
            },
        },

    })

</script>
</body>
</html>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>